import type { QueuePatient } from "../types/doctor-appointments.types";

export const MOCK_QUEUE: QueuePatient[] = [
  {
    id: "p1",
    salutation: "Mr.",
    name: "Rohit Singh",
    age: 34,
    gender: "Male",
    bloodGroup: "B+",
    phone: "98765 43210",
    city: "Mumbai",
    state: "MH",
    token: 1,
    isNew: false,
    appointmentTime: "09:00 AM",
    visitType: "Follow-Up",
    appointmentType: "Telephonic",
    diagnoses: ["Major Depressive Disorder", "Anxiety NOS"],
    allergies: [
      { allergen: "Penicillin", severity: "severe" },
      { allergen: "Sulfa drugs", severity: "moderate" },
    ],
    flag: { label: "High Risk", color: "#dc2626", bg: "#fef2f2" },
    natureBadge: ["Aggressive", "Self-Harm"],
    vitals: {
      bp: "148/92", pulse: "88", spo2: "97", temp: "98.6",
      rr: "18", weight: "78", height: "172", bmi: "26.4",
    },
  },
  {
    id: "p2",
    salutation: "Mrs.",
    name: "Priya Sharma",
    age: 28,
    gender: "Female",
    bloodGroup: "O+",
    phone: "91234 56789",
    city: "Pune",
    state: "MH",
    token: 2,
    isNew: true,
    appointmentTime: "09:30 AM",
    visitType: "New Consultation",
    appointmentType: "Walk-In",
    diagnoses: ["Bipolar Disorder Type II"],
    allergies: [{ allergen: "Aspirin", severity: "mild" }],
    natureBadge: "Suicidal Ideation",
    vitals: {
      bp: "118/76", pulse: "72", spo2: "99", temp: "98.2",
      rr: "16", weight: "58", height: "163", bmi: "21.8",
    },
  },
  {
    id: "p3",
    salutation: "Mr.",
    name: "Karan Shah",
    age: 45,
    gender: "Male",
    bloodGroup: "A+",
    phone: "99887 76654",
    city: "Surat",
    state: "GJ",
    token: 3,
    isNew: false,
    appointmentTime: "10:00 AM",
    visitType: "Follow-Up",
    appointmentType: "Doctor",
    diagnoses: ["Schizophrenia", "Type 2 Diabetes"],
    emergencyContact: true,
    emergencyPhone: "98000 11223",
    vitals: {
      bp: "135/85", pulse: "94", spo2: "96", temp: "99.1",
      rr: "20", weight: "92", height: "175", bmi: "30.0",
    },
  },
  {
    id: "p4",
    salutation: "Ms.",
    name: "Meena Gupta",
    age: 22,
    gender: "Female",
    bloodGroup: "AB-",
    phone: "87654 32100",
    city: "Ahmedabad",
    state: "GJ",
    token: 4,
    isNew: true,
    appointmentTime: "10:30 AM",
    visitType: "New Consultation",
    appointmentType: "E-mail",
    diagnoses: ["Generalized Anxiety Disorder"],
    allergies: [
      { allergen: "Latex", severity: "moderate" },
      { allergen: "Ibuprofen", severity: "mild" },
      { allergen: "Codeine", severity: "severe" },
    ],
    flag: { label: "VIP", color: "#7c3aed", bg: "#f5f3ff" },
    vitals: {
      bp: "110/70", pulse: "68", spo2: "98", temp: "97.8",
      rr: "14", weight: "52", height: "158", bmi: "20.8",
    },
  },
];

export const MOCK_ATTENDED: QueuePatient[] = [
  {
    id: "a1",
    salutation: "Dr.",
    name: "Arvind Patel",
    age: 55,
    gender: "Male",
    bloodGroup: "O-",
    phone: "70000 12345",
    city: "Vadodara",
    state: "GJ",
    token: 101,
    isNew: false,
    appointmentTime: "08:00 AM",
    visitType: "Follow-Up",
    appointmentType: "Telephonic",
    diagnoses: ["OCD", "Insomnia"],
    vitals: {
      bp: "122/80", pulse: "76", spo2: "98", temp: "98.4",
      rr: "17", weight: "70", height: "168", bmi: "24.8",
    },
  },
  {
    id: "a2",
    salutation: "Mrs.",
    name: "Sunita Joshi",
    age: 40,
    gender: "Female",
    bloodGroup: "B-",
    phone: "82222 33344",
    city: "Nashik",
    state: "MH",
    token: 102,
    isNew: false,
    appointmentTime: "08:30 AM",
    visitType: "Follow-Up",
    appointmentType: "Walk-In",
    diagnoses: ["PTSD", "Panic Disorder"],
    allergies: [{ allergen: "Benzodiazepines", severity: "severe" }],
    flag: { label: "Follow-Up Due", color: "#d97706", bg: "#fffbeb" },
    vitals: {
      bp: "126/82", pulse: "80", spo2: "97", temp: "98.8",
      rr: "18", weight: "65", height: "162", bmi: "24.8",
    },
  },
];