import type { HistoryPatient } from "../types/doctor-patients.types";

export const MOCK_PATIENTS: HistoryPatient[] = [
  {
    id: "hp1",
    mrn: "MRN-2024-001",
    salutation: "Mr.",
    name: "Rajesh Kumar",
    age: 45,
    gender: "Male",
    bloodGroup: "B+",
    phone: "+91 98765 43210",
    city: "Mumbai",
    state: "Maharashtra",
    emergencyContact: true,
    emergencyPhone: "+91 91234 56789",
    isNew: false,
    visits: 2,
    lastVisit: "12 Jan 2025",
    attendedAt: "09:10 AM",
    lastDiag: "Generalized Anxiety Disorder",
    visitType: "follow-up",
    appointmentType: "walk-in",
    flag: { label: "Follow-up", bg: "#fef9c3", color: "#ca8a04" },
    natureBadges: ["Anxious", "Chronic"],
    allergies: [{ allergen: "Penicillin" }, { allergen: "Dust" }],
    lastPrescription: [
      { drug: "Sertraline",  dose: "50mg",  freq: "OD",  duration: "30 days" },
      { drug: "Clonazepam", dose: "0.5mg", freq: "SOS", duration: "10 days" },
      { drug: "Melatonin",  dose: "3mg",   freq: "HS",  duration: "15 days" },
    ],
    vitals: { bp: "138/88", pulse: "82", spo2: "97", temp: "98.6", rr: "16", weight: "78", height: "172", bmi: "26.4" },
  },
  {
    id: "hp2",
    mrn: "MRN-2024-002",
    salutation: "Ms.",
    name: "Priya Sharma",
    age: 28,
    gender: "Female",
    bloodGroup: "A+",
    phone: "+91 99887 76655",
    city: "Delhi",
    state: "Delhi",
    isNew: true,
    visits: 1,
    lastVisit: "12 Jan 2025",
    attendedAt: null,
    lastDiag: "Pending",
    visitType: "check-up",
    appointmentType: "telephonic",
    flag: { label: "New", bg: "#dcfce7", color: "#16a34a" },
    natureBadges: ["First Visit"],
    allergies: [],
    lastPrescription: [],
    vitals: { bp: "110/70", pulse: "76", spo2: "99", temp: "98.2", rr: "14", weight: "55", height: "163", bmi: "20.7" },
  },
  {
    id: "hp3",
    mrn: "MRN-2024-003",
    salutation: "Mr.",
    name: "Amit Patel",
    age: 62,
    gender: "Male",
    bloodGroup: "O+",
    phone: "+91 97654 32109",
    city: "Ahmedabad",
    state: "Gujarat",
    emergencyContact: true,
    emergencyPhone: "+91 93456 78901",
    isNew: false,
    visits: 1,
    lastVisit: "15 Dec 2024",
    attendedAt: "10:20 AM",
    lastDiag: "Primary Insomnia",
    visitType: "follow-up",
    appointmentType: "doctor",
    flag: { label: "High Risk", bg: "#fee2e2", color: "#dc2626" },
    natureBadges: ["Elderly", "Chronic"],
    allergies: [{ allergen: "Aspirin" }],
    lastPrescription: [
      { drug: "Zopiclone",  dose: "7.5mg", freq: "HS",     duration: "14 days" },
      { drug: "Melatonin",  dose: "3mg",   freq: "HS",     duration: "30 days" },
      { drug: "Vitamin D",  dose: "60K IU",freq: "Weekly", duration: "8 weeks" },
    ],
    vitals: { bp: "148/92", pulse: "68", spo2: "95", temp: "97.8", rr: "18", weight: "82", height: "168", bmi: "29.1" },
  },
  {
    id: "hp4",
    mrn: "MRN-2024-000",
    salutation: "Mrs.",
    name: "Sunita Desai",
    age: 35,
    gender: "Female",
    bloodGroup: "AB+",
    phone: "+91 96543 21098",
    city: "Pune",
    state: "Maharashtra",
    emergencyContact: true,
    emergencyPhone: "+91 92345 67890",
    isNew: false,
    visits: 1,
    lastVisit: "15 Dec 2024",
    attendedAt: "10:00 AM",
    lastDiag: "Major Depressive Disorder",
    visitType: "follow-up",
    appointmentType: "walk-in",
    flag: { label: "Urgent", bg: "#fff7ed", color: "#ea580c" },
    natureBadges: ["Chronic"],
    allergies: [{ allergen: "Sulfa" }, { allergen: "Latex" }],
    lastPrescription: [
      { drug: "Escitalopram", dose: "10mg",  freq: "OD", duration: "30 days" },
      { drug: "Clonazepam",   dose: "0.25mg",freq: "BD", duration: "15 days" },
    ],
    vitals: { bp: "122/80", pulse: "88", spo2: "98", temp: "99.1", rr: "17", weight: "61", height: "158", bmi: "24.4" },
  },
];